### ISSUE TITLE
track currency balances for accounts

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#104]
### Acceptance criteria
- [ ] Additionally track currency balances in accounts
    - [ ] Investments / Redemptions
    - [x] Transfer IN / OUT
    - [ ] All except CFG TRX

**Comment by filo87** [comment]
@offerijns I cannot find any currency transfer (Withdrawl, deposits and transfers) with both ormlToken and restrictedTokens pallet events. 

I set up logging for all events... but I always get only tranche token transfers...

 Are there any funding or withdrawal of currency tokens on the dev node?

**Comment by offerijns** [comment]
@filo87 Just did a transfer, hopefully this works: https://polkadot.js.org/apps/?rpc=wss://fullnode.development.cntrfg.com#/explorer/query/0xf72c5577e03acd171cd8e5e89de3a3c6bf1e79b73626b1226f303fa104afbe61

**Comment by offerijns** [comment]
This is how you can query token balances:
<img width="1800" alt="Screenshot 2022-10-11 at 08 16 30" src="https://user-images.githubusercontent.com/1748621/195101272-7bcaf064-9892-46b0-9da1-356bee2742e9.png">

So basically `ormlTokens.accounts(account, currency).free`.
