### ISSUE TITLE
compile high-level documentation for subql

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#110]
### Acceptance criteria
- Reference doc: Reference doc: https://docs.aave.com/developers/v/2.0/getting-started/using-graphql
- Documentation would end up on a page like this: https://deploy-preview-391--documentation-staging.netlify.app/build/cent-chain/

**Comment by filo87** [comment]
https://hackmd.io/qNwbSic1Tmqhm2vU-Hj7rQ?both
