### ISSUE TITLE
Extend KPIs as from Spreadsheet

### ISSUE THREAD

**Issue by filo87** [embrio-tech/centrifuge-subql#115]
Index the data highlighted in blue from the spreadsheet below:

https://docs.google.com/spreadsheets/d/1-lp1cYIy5B9Kpni3hLo2UqDD76aDxMimZW_6MbhqiQ4

**Comment by sandford-ch** [comment]
@offerijns : We found a chainState method called uniques.instanceMetadataOf(collectionId, itemId). The method delivers the following items:
- data
- deposit

Few questions:
- deposit: Is deposit equal to collateral value? Does it change over time? Which events do modify it?
- data: Is this the public metadata we were talking about?
Advance rate: Can this be calculated as `Loan/deposit` divided by principal amount (`LoanState/totalBorrowed`)?

`LoanlState/WrittenOff`: We calculate it based on the `LoanState/outstandingDebt` (from last Midnight) * `LoanState/writtenOffPercentage` - is this correct?
