### ISSUE TITLE
Implement custom types for POOLS chain state getters

### ISSUE THREAD

**Issue by filo87** [embrio-tech/centrifuge-subql#13]

**Comment by filo87** [comment]
Opened an issue in polkadot js:

https://github.com/polkadot-js/api/issues/4837

**Comment by oblak1** [comment]
Hi @filo87, I was wondering how you solved this issue with `Error: TypeDefInfo.Enum: Not implemented on`. By cloning this repo and trying it gives me the same error. I also tried using local metadata.json but same result.
