### ISSUE TITLE
Foundations for multi-chain support

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#157]
### Why

Due to the latest implementation of cross-chain bridges, tranche tokens can be transferred to other chains

### What

- [x] solution design for track allocation of tranche tokens to foreign wallets (e.g. Ethereum, Bitcoin, etc.)
- [x] get inputs from Jeroen

### How

- [ ] Initialise multi chain project
- [ ] Handle configuration of multiple EVM chains
- [ ] Update deployment pipeline to work with multichain deployments
- [ ] Concept to inject secrets securely (such as dedicated node API_KEYS)

**Comment by filo87** [comment]
- What tokens, smart contracts?
- On what chains?

What states beside ownership of tokens?

**Comment by hieronx** [comment]
Indexing Liquidity Pools
- Tracking invest/redeem orders based on the account ID derived from the EVM address on Centrifuge Chain
  - Should already fully work, just need to confirm
- Tracking `TRANSFER_IN` and `TRANSFER_OUT` on any EVM chain
  - Add `PoolManager` contract as data source
  - Any time `DeployTranche` event is emitted, set up a dynamic data source for listening to `Transfer` events on the ERC20 token
  - Track balance per account based on `Transfer` events

Sample PoolManager (on goerli): https://goerli.etherscan.io/address/0xDa4A35313b28f70bA06D3e64C15d1e87a35B6F45

Sample Tranche Token (currently unverified, will be verified soon): https://goerli.etherscan.io/address/0x0420bd741A155Ae303997cf444bCDF7622B30820

**Comment by filo87** [comment]
Goerli to Demo Link

**Comment by filo87** [comment]
InvenstorTransactioon on CFG to be linked With ETH address

**Comment by filo87** [comment]
Solution Design:

- V1
    - When `InvestorTransaction` event comes in on Centrifuge network, check if `Account.id` is an EVM account. If so, create `EVMAccount` entity
    - When `Transfer` event comes in on EVM network, look up Account based on `EVMAccount` and create `InvestorTransaction`  for this account with `type` = `TRANSFER_IN/OUT` .
    - Also update CurrencyBalance accordingly
- V2
    - Support `TransferTrancheTokensToCentrifuge` and `TransferTrancheTokensToEVM` events on `PoolManager`
