### ISSUE TITLE
Standardize tracking of tokens and balances across chains

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#173]

**Comment by hieronx** [comment]
```
id: ID! # CFG address
chainId: SmallInt!
evmAddress: String
```

Add `CENTRIFUGE_CHAIN_EVM_CHAIN_ID` env var per network. Set `Account.chainId to `CENTRIFUGE_CHAIN_EVM_CHAIN_ID` if CFG address is not derived from an EVM adress
