### ISSUE TITLE
Fix token prices of non-mainnet chains

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#176]
### Acceptance criteria

- [ ] (Given)/(When)/(Then)
- [ ] (Given)/(When)/(Then)

**Comment by sandford-ch** [comment]
@hieronx : Could you please specify a bit more, what needs fixing re non-mainnet token prices? :) Either here or also in your original ticket: https://github.com/centrifuge/pools-subql/issues/76

**Comment by hieronx** [comment]
https://github.com/centrifuge/pools-subql/pull/73 this PR hardcoded a change for token price decimals that should only apply to Centrifuge mainnet, but currently applies to all networks
