### ISSUE TITLE
Fixing the duplicate TRANSFER_IN/OUT tx (likely to/from pool accounts)

### ISSUE THREAD

**Issue by filo87** [embrio-tech/centrifuge-subql#177]

**Comment by sandford-ch** [comment]
Transaction types: https://app.centrifuge.io/pools/4139607887/reporting

**Comment by hieronx** [comment]
And select the `Investor transactions` report

**Comment by filo87** [comment]
here’s some details on how to generate all the accounts that should be filtered:
DomainLocator: b"domn + 1 + little_endian_bytes(evm_chain_id) + [0u8; 19]
PoolAccount: b"pool' + little_endian_bytes(pool_id) + [0u8; 20]
InvestmentAccount: b"invs" + little_endian_bytes(pool_id) + tranche_id + [0u8; 4]
