### ISSUE TITLE
Separate cash assets, remove maturity date from subquery data

### ISSUE THREAD

**Issue by hieronx** [embrio-tech/centrifuge-subql#198]
- Rename `Loan*` types to `Asset*`
- Add
```graphql
enum AssetType {
  OnchainCash
  OffchainCash
  Other
}

enum AssetValuationMethod {
  Cash
  DiscountedCashFlow
  OutstandingDebt
  Oracle
}

type Asset @entity {
  ...
  type: AssetType!
  isCash: Boolean! @index
  valuationMethod: AssetValuationMethod!
  ...
}
```
- Create asset and corresponding entities for the pool reserve
   - Pool reserve = `LoanType.OnchainCash`
   - Assets with valuation method `Cash` = `LoanType.OffchainCash`
   - Other assets = `LoanType.Other`
- For assets with `type != LoanTypeOther`, remove the maturity date (even if it is set onchain)
- Rename `BorrowerTransaction` to `AssetTransaction`

**Comment by filo87** [comment]
@hieronx Shall we sat the `AssetType` and `AssetValuationMethod` based on 
``` 
  /**
   * Lookup167: pallet_loans::entities::pricing::Pricing<T>
   **/
  PalletLoansEntitiesPricing: {
    _enum: {
      Internal: 'PalletLoansEntitiesPricingInternalInternalPricing',
      External: 'PalletLoansEntitiesPricingExternalExternalPricing'
    }
  },
  /**
   * Lookup168: pallet_loans::entities::pricing::internal::InternalPricing<T>
   **/
  PalletLoansEntitiesPricingInternalInternalPricing: {
    collateralValue: 'u128',
    valuationMethod: 'PalletLoansValuationValuationMethod',
    maxBorrowAmount: 'PalletLoansEntitiesPricingInternalMaxBorrowAmount'
  },
  ```
  these info? or what would be the best approach? 
  
  What about the valuationMethod in the case of `ExternalPricing`?
