### ISSUE TITLE
Track NAV using runtime API

### ISSUE THREAD

**Issue by hieronx** [embrio-tech/centrifuge-subql#199]
Runtime API: `poolsApi.nav(poolId)`

Type definition: https://github.com/centrifuge/apps/blob/pool-fees-follow-up/centrifuge-js/src/CentrifugeBase.ts#L124

**Comment by filo87** [comment]
@hieronx the link above seems to point to a deleted branch....

> Type definition: https://github.com/centrifuge/apps/blob/pool-fees-follow-up/centrifuge-js/src/CentrifugeBase.ts#L124

do you have an updated one? Or was it merged? because in master I cannot find the method.

**Comment by hieronx** [comment]
https://github.com/centrifuge/apps/blob/3bd0339b1895d1adcc80ce0038a0bd6937e413fa/centrifuge-js/src/CentrifugeBase.ts#L129 here you go @filo87
