### ISSUE TITLE
provide data for loan volume widget

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#4]

**Comment by filo87** [comment]
@sandford-ch Is this total loan volume for a given pool right? or over the entire ecosystem?

**Comment by sandford-ch** [comment]
@filo87 : Yes, it is on pool-level - the same widget should also work on the entire eco-system, but has lower priority, as we focus on pool dashboards for now...

I cannot see a reason for more granular data than daily volumes - but might be worthwile to doublecheck with Jeroen, if this decision is rather consequential... ;)
