### ISSUE TITLE
deploy to kubernetes cluster

### ISSUE THREAD

**Issue by tibohei** [embrio-tech/centrifuge-subql#44]
### User story

> **As** DevOps enthusiast    
**I want** to automatically deploy and release new versions    
**So that** users can always consume the latest version of the API without manual deployment efforts.

### Acceptance criteria

- [ ] automatic deployment to k8s cluster
- [ ] public url with https

### Open Questions

- Who is responsible for hosting and deployment? Centrifuge team or EMBRIO.tech?

**Comment by sandford-ch** [comment]
not relevant anymore (#51 )
