### ISSUE TITLE
single investment orders

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#54]
Test pool (id: 2008099657): https://gist.github.com/offerijns/db1ce412b7f47f3d106d116c56eba6d3

### Acceptance criteria:

- [x] `InvestorTransaction`s are only added, never removed.
- [x] Every update order generates an InvestorTransaction and updates the OutstandingOrder.
- [x] When the order is executed, another InvestorTransaction is created with the execution amount, and the OutstandingOrder is updated.
- [x] On an order of 0, another InvestorTransaction of type cancel is created, and the OutstandingOrder is removed.

**Comment by filo87** [comment]
Unclear how to populate transaction fee. Followup required
