### ISSUE TITLE
implement varying precision per token

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#72]
### Acceptance criteria
- [x] Index precision for different currencies through runtime call:  `ormlAssetRegistry.metadata(currencyId).decimals`
- [x] Edit services to support dynamic precision

To be clarified:
- @offerijns: Will every currency have two precisions (short for amounts and long for prices/yields)? If so, can you pls specify the dynamic decimals per currency?

**Comment by offerijns** [comment]
The precision for the balances in each pool, for both currency amounts and tranche token amounts, are alwasy based on the decimals of the pool currency. This can be retrieved using `ormlAssetRegistry.metadata(currencyId).decimals`.

The precision for prices/yields is fixed at 27.
