### ISSUE TITLE
Add prices to all `investorTransaction` types

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#82]
### Summary

Some `investorTransaction` types do not show/store a price

### Steps to reproduce

Go to: https://pr-999--dev-app-cntrfg.netlify.app/investments/3808048191/reporting
-> Select Investor transaction in Report dropdown in the sidebar

### Current behavior

Some `investorTransactions` types do not show prices(e.g. INVEST_COLLECT, INVEST_ORDER_UPDATE, INVEST_ORDER_CANCEL, ...)

### Expected behavior

Every `investorTransaction` type should show prices.
-> Relevant price = most up-to-date prices
-> store most recent `tokenPrice` in `trancheState` when `investorTransaction` event occurs

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/52602184/186678724-262295e4-89de-4444-b6f5-85344beba8f6.png)

### Possible fixes

- Get tranche `tokenPrice` from RPC and include it in the `investorTransaction` or use the last indexed price

**Comment by filo87** [comment]
Tried different alternatives to call the `api.rpc.pools.trancheTokenPrice(poolid: 'u32', trancheId: '[u8;16]')` however the method never accepts the tranche Id. Tried to pass it as a U8aFixed, Uint8Array, number[], HexString. Seems the polkadot.js library always encodes that value to a string.

```bash
cfg-development-subql-node-1  | 2022-08-31T13:56:20.369Z <sandbox> INFO Compact trancheId: 102,180,220,205,125,141,153,177,68,121,97,20,80,237,27,140 
cfg-development-subql-node-1  | 2022-08-31T13:56:20.380Z <sandbox> ERROR undefined RpcError: -32602: invalid type: string "0x66b4dccd7d8d99b14479611450ed1b8c", expected an array of length 16 at line 1 column 36
```

**Comment by filo87** [comment]
Will just use the latest available price from `trancheState`
