### ISSUE TITLE
index `borrowerTransactions` data types

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#84]
### Acceptance criteria

- [ ] Fill accordingly
https://github.com/embrio-tech/centrifuge-subql/blob/1ea507288bf6768daad0ad888451505b95f1deb9/schema.graphql#L274-L294

**Comment by filo87** [comment]
Facing some issues with populating the `accountId` field as this is not submitted wiith loan events as seen below:

https://github.com/embrio-tech/centrifuge-subql/blob/ba1c3c71192daac26ca311b5dfa8d391dbc346e6/src/api-interfaces/lookup.ts#L951-L999

@offerijns any idea where can we best get this?

**Comment by offerijns** [comment]
@filo87 looks like `event.extrinsic.extrinsic.signer` should contain this, can you try that? If it doesn't work, we can also leave this out for now
