### ISSUE TITLE
Extend loan to time series with state snapshot model

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#95]
### Acceptance criteria
- [x] @sandford-ch:
    - Based on best guess (w/o confirmation from Dennis) -> can still be extended, if required
    - https://docs.google.com/spreadsheets/d/1-lp1cYIy5B9Kpni3hLo2UqDD76aDxMimZW_6MbhqiQ4/edit#gid=1592342509
- [x] extend `loanEntity` data types for time series data (i.e. `loanSnapshots` and `loanStates`)

**Comment by filo87** [comment]
Here only the 

- [ ] indexing of outstandingDebt

is still pending
