### ISSUE TITLE
Solution design index public NFT metadata

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-subql#96]
### User Story
As a centrifuge dev I want public NFT data to be indexed, so I can visualize the details in the app

### Acceptance Criteria
- [x] What are public NFT?
- [x] Where is data available?
- [ ] Where is data used?
- [ ] How does the data mode look like?

**Comment by filo87** [comment]
- [ ] Check for a solutioon for unstructured data with SubQL
- [ ] What aggregation scenarions we have to pre-indexing
- [ ] for numeric values -> min, max, average, median across all loans for a given template in a pool

**Comment by filo87** [comment]
Indexing and aggregation of such values must be solved ad hoc

**Comment by filo87** [comment]
Indexing and aggregation of such values must be solved ad hoc
